parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\Counter\CounterInterface:
            tags: ['app.counter']
        App\Notifier\NotifierInterface:
            tags: ['app.notifier']

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Services\UserCreator:
        arguments:
            $notifiers: !tagged_iterator 'app.notifier'

    App\Counter\CounterFactory:
        arguments:
            - !tagged_locator 'app.counter'
